### ISSUE TITLE
set up issue template in main repo

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#10]

**Comment by JosephMcArthur** [comment]
No time right now to do all this, but throwing some notes:

# Selection types

Delete what isn't applicable:

Region: North America | South America | European Union | Africa | Asia | Global | None

Put a cross in the box:

Region:
[ ] North America 
[ ] South America
[ ] European Union
[ ] Africa
[ ] Asia
[ ] Global
[ ] None

# metadata types & values

* Project name: free text or code
* Project description
* Issue type: task / idea / discussion
* Issue area: ( OA / OD / OE / OS )
* Help needed: From the application form (these need to both be cut down & added to)...
  * Advocacy and Policy [advocacy]
  * Blogging [blogging]
  * Communications / Media Relations [comms]
  * Community / Grassroots Organizing [organizing]
  * Event Logistics [events]
  * Fundraising [fundraising]
  * Graphic Design [graphics]
  * Research on Open Access / Open Education / Open Data [open_research]
  * Social Media Campaigns [social_media]
  * Volunteer Management [volunteers]
  * Video Filming / Editing [videos]

* Region: as above

# instructions

* reminder to use the project form
* tell people they can search by project name?
* let people know the comments will disappear?

**Comment by char-siuu-bao** [comment]
Starting to put a form together from this template here: https://docs.google.com/forms/d/e/1FAIpQLSeD14vJ8OgsL6mXE3vBIoMfiauo3j6sJB-A2NoqdSzSRj0ygA/viewform

**Comment by char-siuu-bao** [comment]
is this set up?

**Comment by char-siuu-bao** [comment]
I think the template should include: 

## **Project MetaData** 
(this can be emailed to them to paste exactly as we email them to do so:)

**Project Name:**
**Contact Project Lead:** maybe email or twitter handle.
**External Site Link (optional):**
**Region**:
**Issue Area:**

## **Project Description** 
[ ask them to insert a paragraph here ] 

## **What are we working on during the do-a-thon? What kinds of support do we need?** 
[ ask them to insert a paragraph or here too ] 

## **How can others contribute?** 
[ ask them to put contributing guidelines here -  maybe we can provide a template for this as well ]

**Comment by JosephMcArthur** [comment]
I've now adapted Lorraine's template here to hide _a lot_ on posting and generally be formatted a little bit more nicely. There is now functionality for a lot of help and support to people, which we can drop copy into whenever. 

I've also made light edits to the email people get to make this simpler. More to do, but this is one hurdle crossed.

**Comment by JosephMcArthur** [comment]
closing, pending more feedback from OC and anything caught in the release testing

**Comment by char-siuu-bao** [comment]
Lol Joeeeee you never did this. But done now!
