### ISSUE TITLE
decide what requirements we have for projects/project leads

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#13]

**Comment by JosephMcArthur** [comment]
Anything immediately come to mind here? Are we thinking simple stuff like "be there on the day", or something more involved?

**Comment by JosephMcArthur** [comment]
Duh @lorrainechu3n. I should learn to read. I can see your requirement that it's about OA / OD / OE. That makes sense, anything else? If not, we can probably have the header be this.

**Comment by char-siuu-bao** [comment]
I'm thinking of linking out to a longer list, but wanted to see if you had
any other ideas - the copy is still a work in progress !!

**Comment by JosephMcArthur** [comment]
I think an extra shout out for the CoC and mirroring Mozilla's

> be a welcoming, enthusiastic, and patient project leader

is worth putting here so have done that.

**Comment by JosephMcArthur** [comment]
I _think_ this is all we can really ask from people at this point. Since it's a monday I think it's odd to say "be available". 

Going to close for now, don't hesitate to re-open if you disagree!
