### ISSUE TITLE
write copy for submit challenge page 

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#16]

**Comment by JosephMcArthur** [comment]
LMK where you're at on this & other copy and where I can provide support. A general look at things suggests you're 100% on the right course but I haven't been super critical about things yet.

**Comment by JosephMcArthur** [comment]
Just reviewed this a bit more and made a few small changes, I think it's looking really rather good (certainly good enough to get feedback). 

Can obviously keep editing after... but I'd suggest we can close this for now! Reopen if you disagree
