### ISSUE TITLE
Figure out workflow for submitting challenges

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#17]
what resources to give them, also how we would push them into project submission halfway through the day

**Comment by char-siuu-bao** [comment]
Form for submitting challenges: https://docs.google.com/forms/d/e/1FAIpQLScliEFPRWlvtn0LoK6-1OejaYLz6OwKMd00jFdsMjQRQTlM1A/viewform

Still need to write auto-reply email for those who have submitted challenge to let them know next steps (e.g. how to get it up on Github) - also need to integrate challenges into the issue template

**Comment by JosephMcArthur** [comment]
okay, we still have a tiny bit of work to get the form set up but we've done 99% of the hard stuff here so closing so we can see what needs work!
