### ISSUE TITLE
Write copy for each sub-design thinking page + create resources for each

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#18]
- [ ] systems mapping page
- [ ] understanding users page 
- [ ] designing solutions page

include examples for each or else it may be too abstract for people who haven't used design thinking language before

**Comment by JosephMcArthur** [comment]
I made a quick version of something here for the workshop calls: https://docs.google.com/presentation/d/18N45l-FvYuzrUTG_IP4exdsk-eYf2NDmTRbhRaaQ4pI/edit#slide=id.p

Only have about ~ 5 minutes... so very open to changes.
