### ISSUE TITLE
for design thinking exercises, find online tools that can help make outputs editable & discussable by remote participants 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#20]
During workshops, it probably make sense to just use big pieces of paper... but we think it's important that before & after the workshops it's possible to collaborate on these. 

Decent options include:
* Google Slides (probably the best if only because most people probably know it)
* https://www.draw.io/ (have seen this used, and after using it for 5 minutes it's pretty straight forwards)

**Comment by char-siuu-bao** [comment]
We can create templates for some of this stuff too ... e.g. user personas.  could even just be a google doc.

**Comment by char-siuu-bao** [comment]
I always thought prezi would be a good workspace for this kind of stuff

**Comment by char-siuu-bao** [comment]
I think we should just remind people they can use big sheet paper but to take photos of their outputs and upload to the github thread regularly (or digitize/transcribe it to a digital output after they're done). I can imagine scenarios where trying to do this all digitally will slow down the brainstorming process.

**Comment by JosephMcArthur** [comment]
Indeed. Perhaps we could have all workshop hosts make threads for their workshop's theme / challenge which could be contributed to throughout and folks could upload photos too. I agree that getting folks set up with these inperson is likely to be less than ideal vs just having paper!

**Comment by JosephMcArthur** [comment]
going to use google slides for digital and planning on have pen & paper + encouragement to upload.
