### ISSUE TITLE
figure out how to stop flicker on load

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#22]
when the site first loads for me I get an unstyled version for an instant before images / css etc load. This is quick and not a bit deal but it would be nice to remove.

**Comment by npscience** [comment]
I also get this.

**Comment by char-siuu-bao** [comment]
@JosephMcArthur let's try "minifying" the CSS file: https://stackoverflow.com/questions/9669138/how-to-optimize-css-file-for-speed#comment12281486_9669138

Can attempt to do this weekend

**Comment by char-siuu-bao** [comment]
OK i think I've gotten rid of this now - it's called a FOUC and i added this code to the head to make ti go away:

```
<style type="text/css">
    .hidden {display:none;}
  </style>
  <script type="text/javascript" src="/scripts/jquery.js"></script>
  <script type="text/javascript">
    $('html').addClass('hidden');
    $(document).ready(function() {    // EDIT: From Adam Zerner's comment below: Rather use load: $(window).on('load', function () {...});
      $('html').show();  // EDIT: Can also use $('html').removeClass('hidden');
     });
  </script>
```

it might still happen for a bit until the cache refreshes (or whatever - IDK the language haha) but when I cleared my cache it works. it's been pushed to the live site now too. 

@JosephMcArthur, I don't think your other changes have been pushed live yet (e.g. with the Github help page) - but just giving you a heads up that these changes are in the live version so you don't overwrite them!
