### ISSUE TITLE
add anchors to key sections (e.g the challenge table)

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#24]
this can allow direct linking to specific sections, which I can already see from some copy will be helpful.

**Comment by char-siuu-bao** [comment]
I've already done this!

**Comment by JosephMcArthur** [comment]
ah, gotcha! It's a shame it's not more visible. Perhaps we should add the same things we did on the dei report? I can probably dig out that code fairly easily if you agree it's helpful for everyone to be encouraged to do that deep linking. 

Otherwise, please feel free to close.
