### ISSUE TITLE
asking remote people to RSVP

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#30]
Should we do this, and if so how / where @lorrainechu3n 

We probably _should_ do this, but to be honest I think if we didn't the world would keep on turning :) The main metric here won't be RSVP's be deeper engagement, and if we miss a few RSVP's to keep that simple I think that's fine.

**Comment by JosephMcArthur** [comment]
Discussed with Lorraine. We don't think it's critical at this point and will likely be a prominent action elsewhere that anyone this engaged would see!

**Comment by char-siuu-bao** [comment]
Ah! I didn't realize this was closed and didn't realize it was something we talked about - I think having an RSVP button would be good to mail blast specifically those interested in participating in the do-a-thon who aren't necessarily taking part in OpenCon live more broadly. I think it might be a different demographic.

**Comment by char-siuu-bao** [comment]
Sorry for being scatterbrained. Was just thinking about adding an RSVP button now - and then remembered vaguely there was an issue around this, haha!

**Comment by JosephMcArthur** [comment]
have suggested a place for this on the frontpage :) 

Let me know what you think.
