### ISSUE TITLE
write tips for project leads & challenge leads

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#33]
e.g. guidelines on how to effectively involve people from a distance, set goals, etc... I feel like you would be better at doing this @JosephMcArthur - happy to continue working on it but I could use your help with writing copy for the site, in general!

**Comment by char-siuu-bao** [comment]
Just jotting some notes down - this should also include (simple) contributing guidelines

**Comment by ghost** [comment]
I'm a Github Comment from Joe's test account. This is **how** I _comment_ on things! Here is a list

1. point one
2. point 2

**Comment by char-siuu-bao** [comment]
Remote vs. Non Remote 
let people know if your remote while leading a project
 if you're in the room, let remote people know how best to contribute

Language

Code of Conduct
