### ISSUE TITLE
how do we surface twitter chat on the site, or do we? 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#34]
Any thoughts @lorrainechu3n? I know we've thought about it as a way to highlight projects.

**Comment by char-siuu-bao** [comment]
Yes! We could do our original idea of having an extra column in sheetsu leading to the project chat. We could ask them to submit a hashtag for their project (ask to keep short) and for them to always include #OpenCon and also #whateverprojecthashtag is in their google form (so it shows up on the OpenCon main feed too), and then we could link the twitter search link right into the google sheetsu sheet.  Would that work?

**Comment by char-siuu-bao** [comment]
OR we can create a special hashtag for OpenCon do-a-thon and then embed a twitter stream that just shows all the twitter do-a-thon activity. Or we could do both this and the above idea. What do you think, @JosephMcArthur?

**Comment by char-siuu-bao** [comment]
I think we decided not to do this? Closing for now.
