### ISSUE TITLE
Collect ~3 projects and challenges from core community members to act as examples on home page (should take down collaborate projects - or ask if they are interested) 

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#35]

**Comment by char-siuu-bao** [comment]
this could also act as a test to run through the submit/workflow process.

**Comment by JosephMcArthur** [comment]
done in #21

**Comment by char-siuu-bao** [comment]
Removed examples - now just have ~3 OC projects and ~3 OC challenges.  We can ask them to take down later if they don't actually want to work on these projects - but will serve as examples for now. Closing for now.
