### ISSUE TITLE
Create template for challenge Github issue post

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#37]
I imagine this will look a little different than the project template!

I think we should ask participants to title the Github issue as their "how might we statement"? 

And then have some metadata (project/challenge, issue area, region—if the problem statement is regional-specific) 

Then, to give some context around the problem - what exactly do they mean, what is some context around how the problem arise or why it feels relevant to them so folks start on the same page.

**Comment by JosephMcArthur** [comment]
cover in #10 ?

**Comment by char-siuu-bao** [comment]
here's the form for submitting challenges: https://docs.google.com/forms/d/e/1FAIpQLScliEFPRWlvtn0LoK6-1OejaYLz6OwKMd00jFdsMjQRQTlM1A/viewform

**Comment by JosephMcArthur** [comment]
> I think we should ask participants to title the Github issue as their "how might we statement"?

Yes, this is in

And then have some metadata (project/challenge, issue area, region—if the problem statement is regional-specific)

> This is in the issue template as is

> Then, to give some context around the problem - what exactly do they mean, what is some context around how the problem arise or why it feels relevant to them so folks start on the same page.

This is now part of the template's suggested things to talk about. 

Generally, I don't think we've quite cracked this yet, in the current template it feels like there could be space for misunderstanding and duplication but at the same time I think we need to see how it's used before we'll really know. 

I'm going to close for now, I think it's good enough for feedback, and we'll discuss and move forwards with some info from users in hand.
