### ISSUE TITLE
Create design thinking workspace templates for various exercises 

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#38]
Already planning to link in resources, but for folks for whom this is new, having a direct template to work on (sort of like a worksheet) may be helpful. Can do after initial release, I think.

**Comment by JosephMcArthur** [comment]
Ah, the comment i just put here: https://github.com/sparcopen/doathon-dev/issues/18#issuecomment-339338231 may have been better here.

**Comment by char-siuu-bao** [comment]
Drafting a little booklet we can print ~30 copies of to put around tables.

much like the slides but condensed to a word doc format to be easier to work with: 

https://docs.google.com/document/d/1WA4RXHmolgidiVpOizz0rsaE8PE_4fRwg1B3XK8jkZU/edit

very empty right now but will port most things over from the slides tomorrow and shouldn't take very long

**Comment by JosephMcArthur** [comment]
https://github.com/sparcopen/doathon-dev/issues/38#issuecomment-342053677 closes the issue. Don't think people will like digital generally, and if they do will convert.
