### ISSUE TITLE
Decide how to get issues tagged fast enough (e.g do we form a group)

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#41]

**Comment by JosephMcArthur** [comment]
made this easier using numbering, which makes this faster to do. 

We also now have a backup plan incase we can't tag fast enough.

**Comment by JosephMcArthur** [comment]
- [ ] add #'s to all metadata

**Comment by char-siuu-bao** [comment]
Reformatted to search according to hashtag - should hopefully work in all links now, etc...

**Comment by char-siuu-bao** [comment]
Closing!!!
