### ISSUE TITLE
set up process for submitting and approving projects

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#42]
## Instructions for Project Leads (displayed on website):

**1. Make sure your project meets our project requirements.** 
Insert text to list requirements. If what you're proposing is more of a problem that you don't quite have a project yet for, you might be interested in checking out our Challenge Submission page instead.

**2. Fill out our project submission form.** 
Access the form here. This tells us a bit more about your project and what kind of support you're looking for. It only takes 5-10 minutes!

**3. Wait for e-mail instructions on how to share your project on Github.**
After you've filled out the form, you'll be emailed instructions on how to share information about your project so others can discover it and contribute! Github is a platform for open source, collaborative working. We'll be using it as a space to manage do-a-thon projects and challenges. Specifically, we are doing this through Github "issues". Each issue will act as a mini discussion thread for each task you want to collaborate on. Please follow the email instrutions carefully so your project includes the correct meta-data, which will allow others to find it easily!

If you don't already have one, you'll need to create a Github account.

**4. Your project will now be discoverable on our Do-a-thon Projects page.** 
Now, others will be able to easily find your project and contribute!

**Comment by char-siuu-bao** [comment]
### Our email instructions, atm: 

** I think we discussed on today's call that any in-person attendees will have projects automatically approved, and then folks outside the room will through a quick approval process._  So this email will be automatically emailed to anyone who fills out the form who is an OpenCon 2017 in-person attendee. It will be sent out as a mail merge to those who are remote participants.** 

**Subject**: {First Name}, Your OpenCon Do-A-Thon project has been approved! Next steps:

Hi {First Name},

Thanks so much for submitting your project to the OpenCon 2017 Do-a-Thon! We're excited about your project. The next step is to get information about your project on our Github Issues page, where others will be able to discover and learn more about what types of support you need.  

**Please follow the following steps carefully:** 

**1) If you don't have one already, create a Github account!** Github is a platform for open source, collaborative working. We'll be using it as a space to manage do-a-thon projects—including yours! 

**2) Share what kind of help you need by posting a Github issue at this link.** This will act as a discussion thread where people can work together and talk about what your project needs. 

**3) Give your issue a title**. If your project has a name, it should include the project name, followed by a brief summary of what you need help with. 

E.g. Open Speakers Database: Creating Translated Versions of Website

or, if you don't have a project name, include a one-liner describing you're trying to do:

E.g. Translating searchable database of experts on Open Research & Education 

4) Start your issue by pasting in your Project Name & Description, exactly as below:  

Project name: {Project Name}

Project description: {Project Summary}

5) Now you can elaborate! Give some more information about your project and what kind of support you are looking for. We recommend that this isn't any longer than a paragraph, but if you need to add more detail, feel free to do so! 

6) Include project metadata at the bottom of your issue. Please copy and paste the following text (exactly as it appears) into your issue. This helps provide the correct metadata so others can easily search for your project! 

Issue area: {Issue Area}

Help needed: {Support Categories}

Region: {Region}

We'll come in to add some labels to your issue so it's documented properly, and then you're good to go! Keep your eye on your issue discussion thread for updates from collaborators, and follow these tips for effectively leading a project during the do-a-thon.

Good luck!

Joe & Lorraine

**Comment by char-siuu-bao** [comment]
example of mail merge: 
<img width="946" alt="screen shot 2017-10-17 at 3 40 28 pm" src="https://user-images.githubusercontent.com/10004206/31685607-8d80b83c-b351-11e7-964b-9e018905ee7e.png">

**Comment by char-siuu-bao** [comment]
The responses get put into [this sheetsu spreadsheet](https://docs.google.com/a/sparcopen.org/spreadsheets/d/1L6F_PfkozdCOhuHNhNGk-y9QZMyXEJ9QVf3saU0ET7g/edit?usp=drive_web), which displays on the projects page. We need to get examples into Github and label the issues so we can test out the front end of the sorting system. @JosephMcArthur if you get a chance to get this set-up.  If not, I'll do my best to get it done based off the example you walked through.

**Comment by JosephMcArthur** [comment]
Email Lorraine with details on this (which I suppose could be slightly sensitive.

**Comment by JosephMcArthur** [comment]
- [x] @lorrainechu3n the sheetsu for projects / challenges will now need to show from a sheet called "Sheetsu". This will show only approved projects

**Comment by JosephMcArthur** [comment]
we've largely got this set-up and I think it looks great having tested it! Need to duplicate for projects but that's in the works. Closing for now unless there is something I'm missing.
