### ISSUE TITLE
Capture outputs from the doathon

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#51]

**Comment by JosephMcArthur** [comment]
Discussed this briefly with Lorraine today and have thought about for a while. We've considered:
* a special hashtag for any issue that alerts people to an output. This could then be searched on. 
* a special issue for people to post on when they have an output
* a special form for outputs to go in

I don't think we have a definative answer... but I think there needs to be only one answer and it needs to be simple and easy to remember. We'll really want to make sure that people do this! 

Finally, we of course noted that every issue and comment is going to be an output... it's just about making it discoverable.

**Comment by char-siuu-bao** [comment]
Also moving this to OpenCon 2017 milestone! Doesn't seem pressing for soft launch.

**Comment by char-siuu-bao** [comment]
** let's clarify what "capture outputs" means @JosephMcArthur

**Comment by JosephMcArthur** [comment]
- [x] make a speadsheet for staff / OC to stick issues they think would be good to highlight in some way.

**Comment by JosephMcArthur** [comment]
going to follow up with people from this year. With that, this is okay to close, our mechanisms for this didn't work fantastically but coped at this scale I think.
