### ISSUE TITLE
create language guidelines

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/doathon-dev#52]
We should let people know that they can participate in Github in their own language - esp. for regional based projects, that will be easier. Just have guidelines around making sure metadata is consistently in English for tagging and organization reasons.

**Comment by JosephMcArthur** [comment]
We could have a merge field in the instructions email if people chose regions where people don't speak english as a 1st language that they can do this?

**Comment by JosephMcArthur** [comment]
Add a note on this to:
- [x] the issue template
- [x] the emails sent with instructions

**Comment by char-siuu-bao** [comment]
Also add on tips for project and challenge leads
