### ISSUE TITLE
How might we find author accepted manuscripts to make the process of self archiving easier for them? 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#56]
[//]: # "=======================
Even if you know Github well, we suggest you read this. Anything between these lines you can leave or delete, as they won't display anyway when you post (you can check this via Preview changes). They're here to help you complete issues quickly and in a way that will help other participants. If you're posting a new project, or challenge. We suggest you fill out the Google Forms first.
============================"

#### At a glance

[//]: # "=======================
Please paste the metadata you received after submitting your project or challenge in your Google Form exactly as we sent it to you.
============================"

Submission name: How might we find author accepted manuscripts to make the process of self archiving easier for them? 
Issue area: #Open Access
Region: #Global
Issue Type: #Challenge

#### Description
[//]: # "=======================
Insert a paragraph providing more context for your project or challenge focuses on. For project leads, this is a good place to give some broader context about your project—beyond the scope of the do-a-thon.
============================"

Authors currently send oab a lot of copies that aren't legal and it makes us sad. We'd like to change that. 

#### What are we working on during the do-a-thon? What kinds of support do we need?
[//]: # "=======================
For those leading projects, please give some more information about what type of support you are specifically looking to get done during the do-a-thon day.
Note: Challenge leads will not need to fill out this section and can remove it.
============================"

If you've ever submitted a paper, I need you to show me the submission system! 

####  How can others contribute?
[//]: # "=======================
Please include contributing guidelines here. Let folks know how they get in contact with you, and what the best way to contribute to the project or challenge is. E.g. if you are a challenge lead, give some context on what design thinking tools you'll be using, and how other folks can update their ideas onto the thread.
============================"

Message me on here and we can arrange a screenshare or sit next to each other (radical)

_This post is part of the OpenCon 2017 Do-A-Thon. Not sure what's going on, [head here](doathon.opencon2017.org)_

**Comment by char-siuu-bao** [comment]
this is an example issue so i'm closing to clean up the issues list !
