### ISSUE TITLE
Write a full release blog

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#60]

**Comment by char-siuu-bao** [comment]
First pass here: https://docs.google.com/a/sparcopen.org/document/d/1bm5Uh0yvkVsbVxWMneT1EFwYM-UlSRQ-0Cmr1bx4ark/edit?usp=sharing

pulled mostly from email text sent to in person attendees. aim to get out by monday/tuesday

**Comment by char-siuu-bao** [comment]
http://www.opencon2017.org/invited_to_participate_opencon_doathon

It's up!
