### ISSUE TITLE
respond to https://github.com/sparcopen/opencon/issues/4 with changes

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#64]

**Comment by char-siuu-bao** [comment]
I've hit some, but not all of this.

**Comment by JosephMcArthur** [comment]
have added to do's and some comments here

**Comment by JosephMcArthur** [comment]
okay! I've done everything fast here. Other stuff will probably need more than I'll be able to do now.

**Comment by JosephMcArthur** [comment]
okay, done a few slower things there and updated people.

**Comment by JosephMcArthur** [comment]
moving to the next issue, everything else I think will take more time than we have today
