### ISSUE TITLE
project name shows link, but often isn't linked

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#67]
Lorraine, I know we've fixed this elsewhere, or at least have the code. Would be good to fix asap.

**Comment by char-siuu-bao** [comment]
I'll look into this now! I emailed about it for the speakers database, but never got a chance to implement. will look in my email inbox

**Comment by char-siuu-bao** [comment]
OK should be an easy fix, I think! Doing it now!

**Comment by char-siuu-bao** [comment]
Hmm - it's not working. I think we can figure out before OpenCon 2017 but for now, I'm going to suggest taking out project links entirely but templating it into the github issue metadata.

**Comment by char-siuu-bao** [comment]
Took out the project links entirely - they're linked into the github issue, closing this for now.
