### ISSUE TITLE
Claiming space and signaling location of groups

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/doathon-dev#72]
Nick has asked how we plan to help groups meet at the event. 

Seems like there are quite a few ways this could be done. One thing we can certainly do is put up the table names. Then people can signal better where they are. 

Would love to know what @lorrainechu3n thinks!

**Comment by JosephMcArthur** [comment]
Have suggested that we speak about how to claim space in the intro on Monday. Won't be needed before that and is only needed for in-person people. 

cc @nshockey who was most concerned about this.

**Comment by char-siuu-bao** [comment]
Easy, can add to comms the morning of as a reminder!
